### ISSUE TITLE
POST not supported?

### ISSUE THREAD

**Issue by shuchihlin** [CloudSlang/cloudslang-webapp#6]
Test steps:
1. Downloaded, built and ran the webapp 0.0.1
2. Used curl to send GET requests OK
3. Used curl to send POSTrequests got "405 Method Not Allowed". Maybe missing config setup/change?

Sample request and response:
# curl -v -X POST -d "@/tmp/post_body" "http://admin:admin@x.x.x.x:8080/cs/rest/flows/v1/executions"
Note: Unnecessary use of -X or --request, POST is already inferred.
.
* Server auth using Basic with user 'admin'
> POST /cs/rest/flows/v1/executions HTTP/1.1
> Host: 135.25.187.245:8080
> Authorization: Basic YWRtaW46YWRtaW4=
> User-Agent: curl/7.47.0
> Accept: */*
> Content-Length: 227
> Content-Type: application/x-www-form-urlencoded
>
* upload completely sent off: 227 out of 227 bytes
< HTTP/1.1 **405 Method Not Allowed**
< Server: Apache-Coyote/1.1
< X-Content-Type-Options: nosniff
< X-XSS-Protection: 1; mode=block
< Cache-Control: no-cache, no-store, max-age=0, must-revalidate
< Pragma: no-cache
< Expires: 0
< X-Frame-Options: DENY
< **Allow: HEAD, GET**
< Content-Type: application/json;charset=UTF-8
< Transfer-Encoding: chunked
< Date: Wed, 05 Jul 2017 23:27:09 GMT
<
* Connection #0 to host 135.25.187.245 left intact
{"timestamp":1499297229027,"status":405,"error":"Method Not Allowed","exception":"org.springframework.web.HttpRequestMethodNotSupportedException","message":"Request method 'POST' not supported","path":"/cs/rest/flows/v1/executions"}

# cat /tmp/post_body
           {
               "slangFlowId": "io.cloudslang.y.z",
               "runInputs": {
               "input1" : "value1"
               },
               "systemProperties": {}

**Comment by andreivasiletruta** [comment]
@shuchihlin for the POST you need to trigger the executions related API which should be similar to:

`POST: http://<FQDN>:8080/cs**/rest/v1/executions**`

let me know if it works for you

**Comment by shuchihlin** [comment]
Thank you, Andrei. I just realized I referenced "/cs/rest/**flows/**v1/executions" in my API call by mistake. The POST was OK after the correction.
